'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {satReadingWritingModule1} from '@/data/sat/reading-writing/module-1';
import type {Question} from '@/types/question';
const BANK='american-platform-question-bank-v2', PRACTICE='american-platform-selected-practice-v1';
function load():Question[]{try{const bank:Question[]=JSON.parse(localStorage.getItem(BANK)||'null')||satReadingWritingModule1,ids:string[]=JSON.parse(localStorage.getItem(PRACTICE)||'[]');return ids.map(id=>bank.find(q=>q.id===id)).filter(Boolean) as Question[]}catch{return []}}
export default function Page(){const [qs,setQs]=useState<Question[]>([]),[i,setI]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[done,setDone]=useState(false);useEffect(()=>setQs(load()),[]);const score=useMemo(()=>qs.filter(q=>answers[q.id]===q.correctChoiceId).length,[qs,answers]);const q=qs[i];
 if(!qs.length)return <main className="practice-empty" dir="rtl"><section><h1>لا توجد أسئلة مختارة</h1><p>ارجع لبنك الأسئلة واختر الأسئلة أولًا.</p><Link href="/question-bank">بنك الأسئلة</Link></section></main>;
 if(done)return <main className="practice-result" dir="rtl"><section><span>Practice Complete</span><h1>أحسنت 👏</h1><div className="practice-score"><b>{score}</b><small>من {qs.length}</small></div><p>نسبة الإجابات الصحيحة {Math.round(score/qs.length*100)}%</p><div className="result-actions"><Link href="/question-bank">تدريب جديد</Link><button onClick={()=>{setDone(false);setI(0);setAnswers({})}}>إعادة المحاولة</button></div></section></main>;
 return <main className="custom-practice-page" dir="rtl"><header><Link href="/question-bank">× خروج</Link><div><b>تدريب مخصص</b><span>السؤال {i+1} من {qs.length}</span></div><em>{Object.keys(answers).length}/{qs.length} تمت الإجابة</em></header><div className="custom-progress"><i style={{width:`${(i+1)/qs.length*100}%`}}/></div><section className="custom-practice-card">{q.passage&&<article className="custom-passage"><span>النص</span><div dangerouslySetInnerHTML={{__html:q.passage}}/></article>}<article className="custom-question"><div className="custom-meta"><span>{q.skill}</span><span>{q.domain}</span></div><h1 dangerouslySetInnerHTML={{__html:q.prompt}}/><div className="custom-choices">{q.choices.map(c=><button key={c.id} className={answers[q.id]===c.id?'selected':''} onClick={()=>setAnswers({...answers,[q.id]:c.id})}><b>{c.id}</b><span dangerouslySetInnerHTML={{__html:c.text}}/></button>)}</div></article></section><footer><button disabled={i===0} onClick={()=>setI(i-1)}>السابق</button><div className="question-dots">{qs.map((x,n)=><button key={x.id} className={`${n===i?'current ':''}${answers[x.id]?'answered':''}`} onClick={()=>setI(n)}>{n+1}</button>)}</div>{i<qs.length-1?<button className="primary" onClick={()=>setI(i+1)}>التالي</button>:<button className="primary" onClick={()=>setDone(true)}>إنهاء التدريب</button>}</footer></main>}
