'use client';

import {useMemo, useRef, useState} from 'react';
import Link from 'next/link';
import {satReadingWritingModule1} from '@/data/sat/reading-writing/module-1';
import type {Difficulty, Question, SectionCode} from '@/types/question';

const STORAGE_KEY='american-platform-question-bank-v2';
const TAXONOMY_KEY='american-platform-question-taxonomy-v1';
const CATEGORY_TAG='category:';
const ids=['A','B','C','D'];

type Category={id:string;name:string;systemSection:SectionCode;lessons:string[]};
type Taxonomy={categories:Category[]};
const defaultTaxonomy:Taxonomy={categories:[
  {id:'reading',name:'Reading',systemSection:'READING_WRITING',lessons:['Central Ideas and Details','Command of Evidence','Inferences','Words in Context','Text Structure and Purpose','Cross-Text Connections']},
  {id:'writing',name:'Writing',systemSection:'READING_WRITING',lessons:['Transitions','Rhetorical Synthesis','Boundaries','Form, Structure, and Sense']},
  {id:'math',name:'Math',systemSection:'MATH',lessons:['Algebra','Advanced Math','Problem-Solving and Data Analysis','Geometry and Trigonometry']}
]};
const cloneTaxonomy=():Taxonomy=>JSON.parse(JSON.stringify(defaultTaxonomy));
const blank=(category:Category=defaultTaxonomy.categories[0]):Question=>({id:`SAT-RW-${Date.now()}`,exam:'SAT',section:category.systemSection,module:1,domain:'Information and Ideas',skill:category.lessons[0]||'',difficulty:'MEDIUM',estimatedTimeSeconds:70,passage:'',prompt:'',choices:ids.map(id=>({id,text:''})),correctChoiceId:'A',explanation:'',commonMistakes:[],tags:[`${CATEGORY_TAG}${category.id}`]});
function load(){if(typeof window==='undefined')return satReadingWritingModule1;try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||satReadingWritingModule1}catch{return satReadingWritingModule1}}
function loadTaxonomy(){if(typeof window==='undefined')return cloneTaxonomy();try{return JSON.parse(localStorage.getItem(TAXONOMY_KEY)||'null')||cloneTaxonomy()}catch{return cloneTaxonomy()}}
function text(html=''){return html.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').trim()}
function categoryIdOf(q:Question,taxonomy:Taxonomy){const tagged=q.tags.find(t=>t.startsWith(CATEGORY_TAG))?.slice(CATEGORY_TAG.length);if(tagged&&taxonomy.categories.some(c=>c.id===tagged))return tagged;if(q.section==='MATH')return taxonomy.categories.find(c=>c.systemSection==='MATH')?.id||taxonomy.categories[0]?.id||'';return ['Expression of Ideas','Standard English Conventions'].includes(q.domain)?(taxonomy.categories.find(c=>c.id==='writing')?.id||taxonomy.categories[0]?.id||''):(taxonomy.categories.find(c=>c.id==='reading')?.id||taxonomy.categories[0]?.id||'')}
function withCategory(q:Question,category:Category){return {...q,section:category.systemSection,tags:[...q.tags.filter(t=>!t.startsWith(CATEGORY_TAG)),`${CATEGORY_TAG}${category.id}`]}}

function RichEditor({label,value,onChange,placeholder,minHeight=130}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;minHeight?:number}){
  const ref=useRef<HTMLDivElement>(null);const [full,setFull]=useState(false);
  const run=(cmd:string,val?:string)=>{ref.current?.focus();document.execCommand(cmd,false,val);onChange(ref.current?.innerHTML||'')};
  const addLink=()=>{const url=window.prompt('اكتب رابط الصفحة');if(url)run('createLink',url)};
  const addImage=()=>{const url=window.prompt('الصق رابط الصورة');if(url)run('insertImage',url)};
  return <div className={`simple-rich ${full?'fullscreen':''}`}><div className="simple-rich-title"><b>{label}</b><button type="button" onClick={()=>setFull(!full)}>{full?'تصغير':'ملء الشاشة'}</button></div><div className="simple-toolbar">
      <select aria-label="نوع الخط" onChange={e=>run('fontName',e.target.value)} defaultValue="Arial"><option>Arial</option><option>Georgia</option><option>Times New Roman</option><option>Tahoma</option><option>Courier New</option></select>
      <select aria-label="حجم الخط" onChange={e=>run('fontSize',e.target.value)} defaultValue="3"><option value="1">صغير جدًا</option><option value="2">صغير</option><option value="3">عادي</option><option value="4">كبير</option><option value="5">أكبر</option><option value="6">عنوان</option><option value="7">عنوان كبير</option></select>
      <button type="button" onClick={()=>run('bold')}><b>B</b></button><button type="button" onClick={()=>run('italic')}><i>I</i></button><button type="button" onClick={()=>run('underline')}><u>U</u></button><button type="button" onClick={()=>run('strikeThrough')}><s>S</s></button>
      <label className="color-tool" title="لون الخط">A<input type="color" onChange={e=>run('foreColor',e.target.value)}/></label><label className="color-tool highlight" title="لون التظليل">▰<input type="color" onChange={e=>run('hiliteColor',e.target.value)}/></label>
      <button type="button" onClick={()=>run('justifyLeft')}>⇤</button><button type="button" onClick={()=>run('justifyCenter')}>≡</button><button type="button" onClick={()=>run('justifyRight')}>⇥</button><button type="button" onClick={()=>run('insertUnorderedList')}>• قائمة</button><button type="button" onClick={()=>run('insertOrderedList')}>1. قائمة</button>
      <button type="button" onClick={addLink}>رابط</button><button type="button" onClick={addImage}>صورة</button><button type="button" onClick={()=>run('subscript')}>X₂</button><button type="button" onClick={()=>run('superscript')}>X²</button><button type="button" onClick={()=>run('undo')}>↶</button><button type="button" onClick={()=>run('redo')}>↷</button><button type="button" onClick={()=>run('removeFormat')}>مسح التنسيق</button>
    </div><div ref={ref} className="simple-editor-area" style={{minHeight}} contentEditable suppressContentEditableWarning data-placeholder={placeholder} dangerouslySetInnerHTML={{__html:value}} onInput={e=>onChange(e.currentTarget.innerHTML)}/></div>
}

export default function SimpleQuestionAdmin(){
 const [taxonomy,setTaxonomy]=useState<Taxonomy>(loadTaxonomy);const [questions,setQuestions]=useState<Question[]>(load);const [editing,setEditing]=useState<Question>(()=>blank(loadTaxonomy().categories[0]||defaultTaxonomy.categories[0]));const [mode,setMode]=useState<'quick'|'advanced'>('quick');const [query,setQuery]=useState('');const [toast,setToast]=useState('');const [preview,setPreview]=useState(false);const [manager,setManager]=useState<'categories'|'lessons'|null>(null);
 const selectedCategoryId=categoryIdOf(editing,taxonomy);const selectedCategory=taxonomy.categories.find(c=>c.id===selectedCategoryId)||taxonomy.categories[0];
 const filtered=useMemo(()=>questions.filter(q=>`${q.id} ${q.skill} ${text(q.prompt)}`.toLowerCase().includes(query.toLowerCase())).slice(0,50),[questions,query]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const persist=(next:Question[])=>{setQuestions(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))};
 const persistTaxonomy=(next:Taxonomy)=>{setTaxonomy(next);localStorage.setItem(TAXONOMY_KEY,JSON.stringify(next))};
 const valid=()=>{if(!selectedCategory)return 'أضف قسمًا أولًا';if(!editing.skill.trim())return 'اختر اسم الدرس';if(!text(editing.prompt))return 'اكتب نص السؤال';if(editing.choices.some(c=>!text(c.text)))return 'أكمل جميع الاختيارات';return ''};
 const save=(nextNew=false,draft=false)=>{const err=valid();if(err&&!draft){notify(err);return}const exists=questions.some(q=>q.id===editing.id);const next=exists?questions.map(q=>q.id===editing.id?editing:q):[editing,...questions];persist(next);notify(draft?'تم حفظ المسودة':'تم حفظ السؤال');if(nextNew&&taxonomy.categories[0])setEditing(blank(taxonomy.categories[0]))};
 const updateChoice=(i:number,value:string)=>{const choices=[...editing.choices];choices[i]={...choices[i],text:value};setEditing({...editing,choices})};
 const duplicate=()=>setEditing({...structuredClone(editing),id:`${editing.id}-COPY-${Date.now().toString().slice(-4)}`});
 const selectCategory=(id:string)=>{const category=taxonomy.categories.find(c=>c.id===id);if(category)setEditing(withCategory({...editing,skill:category.lessons[0]||'',domain:category.systemSection==='MATH'?'Algebra':'Information and Ideas'},category))};
 const addCategory=()=>{const name=window.prompt('اكتب اسم القسم الجديد');if(!name?.trim())return;const id=`category-${Date.now()}`;const category:Category={id,name:name.trim(),systemSection:'READING_WRITING',lessons:[]};persistTaxonomy({categories:[...taxonomy.categories,category]});notify('تمت إضافة القسم')};
 const renameCategory=(category:Category)=>{const name=window.prompt('تعديل اسم القسم',category.name);if(!name?.trim())return;persistTaxonomy({categories:taxonomy.categories.map(c=>c.id===category.id?{...c,name:name.trim()}:c)});notify('تم تعديل اسم القسم')};
 const deleteCategory=(category:Category)=>{const linked=questions.filter(q=>categoryIdOf(q,taxonomy)===category.id);if(linked.length){const targets=taxonomy.categories.filter(c=>c.id!==category.id);if(!targets.length){notify('لا يمكن حذف القسم الوحيد');return}const targetName=window.prompt(`القسم مرتبط بـ ${linked.length} سؤال. اكتب اسم القسم الذي تريد نقل الأسئلة إليه:\n${targets.map(c=>c.name).join(' - ')}`);const target=targets.find(c=>c.name.toLowerCase()===targetName?.trim().toLowerCase());if(!target){notify('لم يتم الحذف: اختر اسم قسم صحيح للنقل');return}persist(questions.map(q=>categoryIdOf(q,taxonomy)===category.id?withCategory({...q,skill:target.lessons[0]||q.skill},target):q));}else if(!window.confirm(`حذف قسم ${category.name}؟`))return;const next={categories:taxonomy.categories.filter(c=>c.id!==category.id)};persistTaxonomy(next);if(selectedCategoryId===category.id&&next.categories[0])setEditing(blank(next.categories[0]));notify('تم حذف القسم')};
 const addLesson=()=>{if(!selectedCategory)return;const name=window.prompt(`اسم الدرس الجديد داخل ${selectedCategory.name}`);if(!name?.trim())return;if(selectedCategory.lessons.some(x=>x.toLowerCase()===name.trim().toLowerCase())){notify('اسم الدرس موجود بالفعل');return}persistTaxonomy({categories:taxonomy.categories.map(c=>c.id===selectedCategory.id?{...c,lessons:[...c.lessons,name.trim()]}:c)});setEditing({...editing,skill:name.trim()});notify('تمت إضافة الدرس')};
 const renameLesson=(oldName:string)=>{if(!selectedCategory)return;const name=window.prompt('تعديل اسم الدرس',oldName);if(!name?.trim())return;persistTaxonomy({categories:taxonomy.categories.map(c=>c.id===selectedCategory.id?{...c,lessons:c.lessons.map(x=>x===oldName?name.trim():x)}:c)});persist(questions.map(q=>categoryIdOf(q,taxonomy)===selectedCategory.id&&q.skill===oldName?{...q,skill:name.trim()}:q));if(editing.skill===oldName)setEditing({...editing,skill:name.trim()});notify('تم تعديل اسم الدرس والأسئلة المرتبطة')};
 const deleteLesson=(lesson:string)=>{if(!selectedCategory)return;const linked=questions.filter(q=>categoryIdOf(q,taxonomy)===selectedCategory.id&&q.skill===lesson);let replacement='';if(linked.length){const choices=selectedCategory.lessons.filter(x=>x!==lesson);if(!choices.length){notify('أضف درسًا آخر أولًا لنقل الأسئلة إليه');return}replacement=window.prompt(`الدرس مرتبط بـ ${linked.length} سؤال. اكتب اسم الدرس البديل:\n${choices.join(' - ')}`)?.trim()||'';if(!choices.some(x=>x.toLowerCase()===replacement.toLowerCase())){notify('لم يتم الحذف: اختر درسًا صحيحًا للنقل');return}replacement=choices.find(x=>x.toLowerCase()===replacement.toLowerCase())||'';persist(questions.map(q=>categoryIdOf(q,taxonomy)===selectedCategory.id&&q.skill===lesson?{...q,skill:replacement}:q));}else if(!window.confirm(`حذف درس ${lesson}؟`))return;persistTaxonomy({categories:taxonomy.categories.map(c=>c.id===selectedCategory.id?{...c,lessons:c.lessons.filter(x=>x!==lesson)}:c)});if(editing.skill===lesson)setEditing({...editing,skill:replacement||selectedCategory.lessons.find(x=>x!==lesson)||''});notify('تم حذف الدرس')};
 return <main className="simple-admin-page" dir="rtl">
   <header className="simple-admin-header"><div><Link href="/">المنصة</Link><span>/</span><b>بنك الأسئلة</b></div><div><Link className="light-btn" href="/admin/questions/import">استيراد جماعي</Link><button className="main-btn" onClick={()=>taxonomy.categories[0]&&setEditing(blank(taxonomy.categories[0]))}>+ سؤال جديد</button></div></header>
   <section className="simple-admin-layout"><aside className="simple-question-side"><div className="side-head"><h2>الأسئلة</h2><b>{questions.length}</b></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الدرس أو السؤال..."/><div className="side-list">{filtered.map(q=>{const cat=taxonomy.categories.find(c=>c.id===categoryIdOf(q,taxonomy));return <button key={q.id} className={q.id===editing.id?'active':''} onClick={()=>setEditing(structuredClone(q))}><span>{cat?.name||'غير مصنف'} · {q.skill}</span><b>{text(q.prompt)||'سؤال بدون نص'}</b><small>{q.difficulty} · {q.id}</small></button>})}</div></aside>
    <section className="simple-authoring"><div className="authoring-top"><div><span>إدخال سؤال</span><h1>{questions.some(q=>q.id===editing.id)?'تعديل السؤال':'سؤال جديد'}</h1><p>كل ما تحتاجه في شاشة واحدة، بدون خطوات معقدة.</p></div><div className="mode-switch"><button className={mode==='quick'?'active':''} onClick={()=>setMode('quick')}>الوضع السريع</button><button className={mode==='advanced'?'active':''} onClick={()=>setMode('advanced')}>خيارات متقدمة</button></div></div>
      <div className="classification-strip"><label><span>القسم</span><div className="managed-select"><select value={selectedCategoryId} onChange={e=>selectCategory(e.target.value)}>{taxonomy.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" onClick={()=>setManager('categories')}>إدارة</button></div></label>
       <label className="lesson-field"><span>اسم الدرس</span><div className="managed-select"><select value={editing.skill} onChange={e=>setEditing({...editing,skill:e.target.value})}><option value="">اختر اسم الدرس</option>{selectedCategory?.lessons.map(x=><option key={x} value={x}>{x}</option>)}</select><button type="button" onClick={()=>setManager('lessons')} disabled={!selectedCategory}>إدارة</button></div></label>
       <label><span>الصعوبة</span><select value={editing.difficulty} onChange={e=>setEditing({...editing,difficulty:e.target.value as Difficulty})}><option value="EASY">سهل</option><option value="MEDIUM">متوسط</option><option value="HARD">صعب</option></select></label></div>
      {mode==='advanced'&&<div className="advanced-grid"><label>الامتحان<select value={editing.exam} onChange={e=>setEditing({...editing,exam:e.target.value as Question['exam']})}><option>SAT</option><option>EST</option><option>ACT</option><option value="BEGINNERS">Beginners</option></select></label><label>Module<input type="number" min="1" value={editing.module} onChange={e=>setEditing({...editing,module:Number(e.target.value)})}/></label><label>Domain<input value={editing.domain} onChange={e=>setEditing({...editing,domain:e.target.value})}/></label><label>الوقت بالثواني<input type="number" min="10" value={editing.estimatedTimeSeconds} onChange={e=>setEditing({...editing,estimatedTimeSeconds:Number(e.target.value)})}/></label><label className="wide">ID<input value={editing.id} onChange={e=>setEditing({...editing,id:e.target.value})}/></label><label className="wide">Tags<input value={editing.tags.filter(t=>!t.startsWith(CATEGORY_TAG)).join(', ')} onChange={e=>setEditing({...editing,tags:[...editing.tags.filter(t=>t.startsWith(CATEGORY_TAG)),...e.target.value.split(',').map(x=>x.trim()).filter(Boolean)]})}/></label></div>}
      <RichEditor label="القطعة أو النص — اختياري" value={editing.passage||''} onChange={v=>setEditing({...editing,passage:v})} placeholder="الصق القطعة هنا، ثم نسّقها كما تريد..." minHeight={160}/><RichEditor label="نص السؤال" value={editing.prompt} onChange={v=>setEditing({...editing,prompt:v})} placeholder="اكتب السؤال هنا..." minHeight={110}/>
      <section className="easy-choices"><div className="section-title"><div><b>الاختيارات</b><span>اضغط على الدائرة لتحديد الإجابة الصحيحة</span></div><button onClick={()=>setEditing({...editing,choices:[...editing.choices].sort(()=>Math.random()-.5)})}>خلط الترتيب</button></div>{editing.choices.map((c,i)=><div className={`easy-choice ${editing.correctChoiceId===c.id?'correct':''}`} key={`${c.id}-${i}`}><label><input type="radio" name="correct" checked={editing.correctChoiceId===c.id} onChange={()=>setEditing({...editing,correctChoiceId:c.id})}/><b>{c.id}</b></label><div contentEditable suppressContentEditableWarning data-placeholder={`اكتب الاختيار ${c.id}`} dangerouslySetInnerHTML={{__html:c.text}} onInput={e=>updateChoice(i,e.currentTarget.innerHTML)}/></div>)}</section>
      <RichEditor label="شرح الإجابة" value={editing.explanation} onChange={v=>setEditing({...editing,explanation:v})} placeholder="اكتب شرحًا بسيطًا لسبب صحة الإجابة..." minHeight={110}/><div className="sticky-save"><div><span>حفظ محلي آمن عند الضغط على الحفظ</span><button className="text-btn" onClick={duplicate}>تكرار السؤال</button></div><div><button className="light-btn" onClick={()=>setPreview(true)}>معاينة كطالب</button><button className="light-btn" onClick={()=>save(false,true)}>حفظ كمسودة</button><button className="light-btn" onClick={()=>save(false,false)}>حفظ</button><button className="main-btn" onClick={()=>save(true,false)}>حفظ وإضافة سؤال جديد</button></div></div>
    </section></section>
   {manager&&<div className="taxonomy-modal" onClick={()=>setManager(null)}><article onClick={e=>e.stopPropagation()}><header><div><small>{manager==='categories'?'تنظيم بنك الأسئلة':'داخل قسم '+selectedCategory?.name}</small><h2>{manager==='categories'?'إدارة الأقسام':'إدارة أسماء الدروس'}</h2></div><button onClick={()=>setManager(null)}>×</button></header>{manager==='categories'?<><button className="taxonomy-add" onClick={addCategory}>+ إضافة قسم جديد</button><div className="taxonomy-list">{taxonomy.categories.map(c=><div key={c.id}><span><b>{c.name}</b><small>{questions.filter(q=>categoryIdOf(q,taxonomy)===c.id).length} سؤال · {c.lessons.length} درس</small></span><button onClick={()=>renameCategory(c)}>تعديل</button><button className="danger" onClick={()=>deleteCategory(c)}>حذف</button></div>)}</div></>:<><button className="taxonomy-add" onClick={addLesson}>+ إضافة درس جديد</button><div className="taxonomy-list">{selectedCategory?.lessons.length?selectedCategory.lessons.map(lesson=><div key={lesson}><span><b>{lesson}</b><small>{questions.filter(q=>categoryIdOf(q,taxonomy)===selectedCategory.id&&q.skill===lesson).length} سؤال</small></span><button onClick={()=>renameLesson(lesson)}>تعديل</button><button className="danger" onClick={()=>deleteLesson(lesson)}>حذف</button></div>):<p className="taxonomy-empty">لا توجد دروس بعد. أضف أول درس للقسم.</p>}</div></>}</article></div>}
   {preview&&<div className="simple-preview-modal" onClick={()=>setPreview(false)}><article onClick={e=>e.stopPropagation()}><button className="preview-close" onClick={()=>setPreview(false)}>×</button>{editing.passage&&<section><small>PASSAGE</small><div dangerouslySetInnerHTML={{__html:editing.passage}}/></section>}<section><small>QUESTION</small><div className="preview-question" dangerouslySetInnerHTML={{__html:editing.prompt}}/><div className="preview-answers">{editing.choices.map(c=><div className={c.id===editing.correctChoiceId?'correct':''} key={c.id}><b>{c.id}</b><span dangerouslySetInnerHTML={{__html:c.text}}/></div>)}</div></section></article></div>}{toast&&<div className="cms-toast">{toast}</div>}
 </main>
}
