export type Question={id:number;domain:string;prompt:string;choices:string[];answer:number;explanation:string};
export const questions:Question[]=[
{id:1,domain:'Information and Ideas',prompt:'Which choice best states the main idea of the text?',choices:['Urban trees are mainly decorative.','Urban trees provide meaningful benefits, but planning determines their long-term value.','All trees provide identical results.','Tree cover has no relationship to city temperature.'],answer:1,explanation:'The text presents several benefits and then qualifies that outcomes depend on selection, placement, and maintenance.'},
{id:2,domain:'Command of Evidence',prompt:'Which finding most directly supports the claim that trees can improve urban comfort?',choices:['Trees are valued for beauty.','Neighborhoods had different tree cover.','Areas with more shade were cooler during the hottest part of the day.','Some species need maintenance.'],answer:2,explanation:'The measured temperature difference directly supports the claim about urban comfort.'},
{id:3,domain:'Words in Context',prompt:'As used in the text, “resilient” most nearly means',choices:['expensive','able to adapt and recover','visually attractive','densely populated'],answer:1,explanation:'In context, resilient cities can better handle heat and environmental stress.'},
{id:4,domain:'Inference',prompt:'What can reasonably be inferred about poorly planned planting programs?',choices:['They may fail to deliver expected long-term benefits.','They always increase flooding.','They cost less than strategic programs.','They require no maintenance.'],answer:0,explanation:'The final paragraph says outcomes depend on species, maintenance, and placement.'},
{id:5,domain:'Transitions',prompt:'Which transition best introduces the final paragraph?',choices:['Similarly,','However,','For example,','Therefore,'],answer:1,explanation:'The final paragraph qualifies the positive claims, so “However” is the logical transition.'}
];
export const passage=`Urban trees are often valued for their beauty, but recent research shows that their benefits extend far beyond appearance. Trees can reduce surface temperatures, improve air quality, and help cities manage stormwater more effectively.\n\nIn one study, researchers compared neighborhoods with different levels of tree cover. Areas with more shade were measurably cooler during the hottest part of the day. The researchers concluded that strategic planting could make dense cities more comfortable and resilient.\n\nHowever, the study also emphasized that not all planting strategies produce equal results. Species selection, maintenance, and placement all influence whether a tree thrives and provides long-term value.`;
