'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {questions} from '@/lib/exam-config';
import {ExamProvider,useExam} from '@/components/exam-store';
import ExamFrame from '@/components/exam-frame';
function Session(){
 const [i,setI]=useState(0);const [focus,setFocus]=useState(false);const [lineHeight,setLineHeight]=useState(2.05);const [menu,setMenu]=useState(false);const [calc,setCalc]=useState(false);const [ref,setRef]=useState(false);const [noteOpen,setNoteOpen]=useState(false);const [shortcuts,setShortcuts]=useState(false);const [font,setFont]=useState(18);const [contrast,setContrast]=useState(false);const [toast,setToast]=useState('');
 const passageRef=useRef<HTMLDivElement>(null);
 const {answers,flags,eliminated,notes,setAnswer,toggleFlag,toggleEliminate,setNote}=useExam();const q=questions[i];const passage=q.passage||'';
 const answered=useMemo(()=>answers.filter(v=>v!==null).length,[answers]);
 const showToast=(msg:string)=>{setToast(msg);window.setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{const raw=new URLSearchParams(window.location.search).get('q');if(raw){const n=Number(raw)-1;if(n>=0&&n<questions.length)setI(n)}},[]);
 useEffect(()=>{const warning=(e:Event)=>{const t=(e as CustomEvent<number>).detail;showToast(t===60?'One minute remaining':`${Math.floor(t/60)} minutes remaining`)};window.addEventListener('exam-time-warning',warning);return()=>window.removeEventListener('exam-time-warning',warning)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(noteOpen||calc||ref||menu||shortcuts)return;if(e.key==='ArrowRight'&&i<questions.length-1)setI(v=>v+1);if(e.key==='ArrowLeft'&&i>0)setI(v=>v-1);if(/^[1-4]$/.test(e.key))setAnswer(i,Number(e.key)-1);if(e.key.toLowerCase()==='m')toggleFlag(i);if(e.key.toLowerCase()==='n')setNoteOpen(true);if(e.key==='?')setShortcuts(true)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[i,noteOpen,calc,ref,menu,shortcuts,setAnswer,toggleFlag]);
 const styleSelection=(mode:'highlight'|'underline')=>{const sel=window.getSelection();if(!sel||sel.rangeCount===0||sel.isCollapsed){showToast('Select text in the passage first');return}const range=sel.getRangeAt(0);if(!passageRef.current?.contains(range.commonAncestorContainer)){showToast('Reading tools work inside the passage');return}try{const el=document.createElement(mode==='highlight'?'mark':'span');el.className=mode==='highlight'?'student-highlight':'student-underline';range.surroundContents(el);sel.removeAllRanges();showToast(mode==='highlight'?'Text highlighted':'Text underlined')}catch{showToast('Select a smaller text segment')}};
 const highlightSelection=()=>styleSelection('highlight');
 return <ExamFrame><main className={`exam-layout premium v4-layout ${contrast?'high-contrast':''} ${focus?'focus-reading':''}`}>
  <section className="passage-pane"><div className="pane-head"><span>Reading Passage</span><div className="inline-tools"><button className="tool" onClick={()=>setFont(v=>Math.max(15,v-1))}>A−</button><button className="tool" onClick={()=>setFont(v=>Math.min(24,v+1))}>A+</button><button className="tool" onClick={highlightSelection}>Highlight</button><button className="tool" onClick={()=>styleSelection('underline')}>Underline</button><button className="tool" onClick={()=>setLineHeight(v=>v>=2.35?1.75:Number((v+.2).toFixed(2)))}>Line spacing</button><button className={`tool ${focus?'active':''}`} onClick={()=>setFocus(v=>!v)}>Focus</button><button className="tool" onClick={()=>setContrast(v=>!v)}>◐</button></div></div><div ref={passageRef} className="passage-copy" style={{fontSize:font,lineHeight}}>{passage.split('\n\n').map((p,x)=><p key={x}>{p}</p>)}</div></section>
  <section className="question-pane" key={i}><div className="pane-head"><div><span>Question {i+1} of {questions.length}</span><small>{q.domain}</small></div><button className={flags[i]?'flag active':'flag'} onClick={()=>toggleFlag(i)}>⚑ Mark for Review</button></div><div className="question-progress"><span style={{width:`${((i+1)/questions.length)*100}%`}}/></div><h2>{q.prompt}</h2><div className="choices">{q.choices.map((c,x)=><div key={c.id} className={`choice-wrap ${answers[i]===x?'selected':''} ${eliminated[i]?.includes(x)?'eliminated':''}`}><button className="choice-main" onClick={()=>setAnswer(i,x)}><b><span>{String.fromCharCode(65+x)}</span></b><span>{c.text}</span></button><button className="strike" aria-label="Eliminate choice" onClick={()=>toggleEliminate(i,x)}>ABC</button></div>)}</div>
  <div className="exam-actions"><button className="utility" onClick={()=>setNoteOpen(true)}>📝 Notes {notes[i]?'•':''}</button><button className="utility" onClick={()=>setCalc(true)}>🧮 Calculator</button><button className="utility" onClick={()=>setRef(true)}>📄 Reference</button><button className="utility" onClick={()=>setShortcuts(true)}>⌨ Shortcuts</button></div>
  <footer className="exam-nav premium-nav"><button disabled={i===0} onClick={()=>setI(v=>v-1)}>Back</button><button className="question-menu-button" onClick={()=>setMenu(true)}>Question {i+1} of {questions.length}⌃</button>{i<questions.length-1?<button className="primary" onClick={()=>setI(v=>v+1)}>Next</button>:<Link className="primary" href="/exams/review">Review</Link>}</footer></section>
 </main>
 {menu&&<div className="overlay"><section className="question-menu"><header><div><b>Questions</b><span>{answered} answered · {flags.filter(Boolean).length} marked</span></div><button onClick={()=>setMenu(false)}>×</button></header><div className="question-grid">{questions.map((_,x)=><button key={x} className={`${x===i?'current ':''}${answers[x]!==null?'answered ':''}${flags[x]?'flagged':''}`} onClick={()=>{setI(x);setMenu(false)}}>{x+1}</button>)}</div><div className="menu-legend"><span><i className="legend-current"/>Current</span><span><i className="legend-answered"/>Answered</span><span>⚑ Marked</span></div></section></div>}
 {noteOpen&&<div className="overlay"><section className="modal-card"><header><b>Question {i+1} Notes</b><button onClick={()=>setNoteOpen(false)}>×</button></header><textarea value={notes[i]||''} onChange={e=>setNote(i,e.target.value)} placeholder="Write a note for this question..."/><button className="primary" onClick={()=>setNoteOpen(false)}>Save note</button></section></div>}
 {calc&&<div className="overlay"><section className="modal-card calculator"><header><b>Built-in Calculator</b><button onClick={()=>setCalc(false)}>×</button></header><FunctionalCalculator/><p className="modal-note">A graphing calculator will be integrated in the Math module.</p></section></div>}
 {ref&&<div className="overlay"><section className="modal-card reference"><header><b>Reference Sheet</b><button onClick={()=>setRef(false)}>×</button></header><div className="formula-grid"><article><b>Circle</b><span>A = πr²</span><span>C = 2πr</span></article><article><b>Triangle</b><span>A = ½bh</span><span>c² = a² + b²</span></article><article><b>Rectangular Prism</b><span>V = lwh</span></article><article><b>Cylinder</b><span>V = πr²h</span></article></div></section></div>}
 {shortcuts&&<div className="overlay"><section className="modal-card"><header><b>Keyboard Shortcuts</b><button onClick={()=>setShortcuts(false)}>×</button></header><div className="shortcut-list"><span><kbd>1–4</kbd>Select answer</span><span><kbd>← / →</kbd>Previous / next</span><span><kbd>M</kbd>Mark for review</span><span><kbd>N</kbd>Open notes</span><span><kbd>?</kbd>Show shortcuts</span></div></section></div>}
 {toast&&<div className="exam-toast">{toast}</div>}
 </ExamFrame>
}
function FunctionalCalculator(){const [display,setDisplay]=useState('0');const [expr,setExpr]=useState('');const press=(v:string)=>{if(v==='C'){setExpr('');setDisplay('0');return}if(v==='='){try{const safe=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-');const result=Function(`"use strict";return (${safe})`)();setExpr(String(result));setDisplay(String(result))}catch{setDisplay('Error')}return}const next=expr+v;setExpr(next);setDisplay(next)};return <><div className="calc-screen">{display}</div><div className="calc-grid">{['C','(',')','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','%','='].map(v=><button key={v} onClick={()=>press(v)}>{v}</button>)}</div></>}
export default function Page(){return <ExamProvider><Session/></ExamProvider>}
