'use client';
import {Suspense,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {buildProfileExam,examHref} from '@/lib/exam-profiles';
import {ExamProvider,useExam} from '@/components/exam-store';
import ExamFrame from '@/components/exam-frame';
function StandardSession(){
 const [i,setI]=useState(0);const [focus,setFocus]=useState(false);const [lineHeight,setLineHeight]=useState(1.75);const [menu,setMenu]=useState(false);const [calc,setCalc]=useState(false);const [ref,setRef]=useState(false);const [noteOpen,setNoteOpen]=useState(false);const [shortcuts,setShortcuts]=useState(false);const [font,setFont]=useState(17);const [contrast,setContrast]=useState(false);const [toast,setToast]=useState('');const [timerHidden,setTimerHidden]=useState(false);const [toolsOpen,setToolsOpen]=useState(false);
 const passageRef=useRef<HTMLDivElement>(null);const stripRef=useRef<HTMLDivElement>(null);
 const {answers,flags,eliminated,notes,setAnswer,toggleFlag,toggleEliminate,setNote,questions,exam,timeLeft,setActiveQuestion}=useExam();const q=questions[i];const passage=q.passage||'';
 const answered=useMemo(()=>answers.filter(v=>v!==null).length,[answers]);const mins=String(Math.floor(timeLeft/60)).padStart(2,'0');const secs=String(timeLeft%60).padStart(2,'0');
 const showToast=(msg:string)=>{setToast(msg);window.setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{const raw=new URLSearchParams(window.location.search).get('q');if(raw){const n=Number(raw)-1;if(n>=0&&n<questions.length)setI(n)}},[questions.length]);
 useEffect(()=>{setActiveQuestion(i);passageRef.current?.scrollTo({top:0,behavior:'smooth'});stripRef.current?.querySelector(`[aria-current="step"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})},[i,setActiveQuestion]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(noteOpen||calc||ref||menu||shortcuts||toolsOpen)return;if(e.key==='ArrowRight'&&i<questions.length-1)setI(v=>v+1);if(e.key==='ArrowLeft'&&i>0)setI(v=>v-1);if(/^[1-4]$/.test(e.key))setAnswer(i,Number(e.key)-1);if(['a','b','c','d'].includes(e.key.toLowerCase()))setAnswer(i,e.key.toLowerCase().charCodeAt(0)-97);if(e.key.toLowerCase()==='m')toggleFlag(i)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[i,noteOpen,calc,ref,menu,shortcuts,toolsOpen,questions.length,setAnswer,toggleFlag]);
 const styleSelection=(mode:'highlight'|'underline')=>{const sel=window.getSelection();if(!sel||sel.rangeCount===0||sel.isCollapsed){showToast('Select text in the passage first');return}const range=sel.getRangeAt(0);if(!passageRef.current?.contains(range.commonAncestorContainer)){showToast('Reading tools work inside the passage');return}try{const el=document.createElement(mode==='highlight'?'mark':'span');el.className=mode==='highlight'?'student-highlight':'student-underline';range.surroundContents(el);sel.removeAllRanges()}catch{showToast('Select a smaller text segment')}};
 return <ExamFrame hideHeader><div className={`sat-shell ${contrast?'sat-contrast':''} ${focus?'sat-focus':''}`} dir="ltr">
  <header className="sat-topbar"><div className="sat-brand">MASTERY <span>SAT Practice</span></div><div className="sat-module"><b>{exam.blueprint.section.replaceAll('_',' & ')}</b><small>Module {exam.blueprint.module}</small></div><button className="sat-timer" onClick={()=>setTimerHidden(v=>!v)}><small>Time Remaining</small><b>{timerHidden?'••:••':`${mins}:${secs}`}</b><span>{timerHidden?'Show':'Hide'}</span></button></header>
  <nav className="sat-toolbar"><button onClick={()=>setMenu(true)}>☷ Question Menu</button><div className="sat-tool-anchor"><button onClick={()=>setToolsOpen(v=>!v)}>⚙ Tools⌄</button>{toolsOpen&&<div className="sat-tool-menu"><button onClick={()=>setFont(v=>Math.min(23,v+1))}>Increase text</button><button onClick={()=>setFont(v=>Math.max(14,v-1))}>Decrease text</button><button onClick={()=>styleSelection('highlight')}>Highlight</button><button onClick={()=>styleSelection('underline')}>Underline</button><button onClick={()=>setLineHeight(v=>v>=2.2?1.55:v+.2)}>Line spacing</button><button onClick={()=>setFocus(v=>!v)}>Focus mode</button><button onClick={()=>setContrast(v=>!v)}>Contrast</button></div>}</div><button onClick={()=>setNoteOpen(true)}>✎ Highlights & Notes</button>{exam.blueprint.section==='MATH'&&<button onClick={()=>setCalc(true)}>▣ Calculator</button>}<button onClick={()=>setRef(true)}>▤ Reference</button></nav>
  <main className="sat-workspace">
   <section className="sat-passage"><header><b>Reading Passage</b></header><article ref={passageRef} style={{fontSize:font,lineHeight}}>{passage.split('\n\n').map((p,x)=><p key={x}>{p}</p>)}</article><footer><button onClick={()=>setFont(v=>Math.min(23,v+1))}>⌕ Zoom</button><span>Word Count: {passage.trim()?passage.trim().split(/\s+/).length:0}</span></footer></section>
   <section className="sat-question" key={i}><header><span>Question {i+1} of {questions.length}</span><button className={flags[i]?'marked':''} onClick={()=>toggleFlag(i)}>♧ Mark for Review</button></header><h1 style={{fontSize:font+1}} dangerouslySetInnerHTML={{__html:q.prompt}}/><div className="sat-choices">{q.choices.map((c,x)=><div key={c.id} className={`sat-choice ${answers[i]===x?'selected':''} ${eliminated[i]?.includes(x)?'eliminated':''}`}><button className="sat-choice-main" onClick={()=>setAnswer(i,x)}><b>{String.fromCharCode(65+x)}</b><span dangerouslySetInnerHTML={{__html:c.text}}/></button><button className="sat-crossout" onClick={()=>toggleEliminate(i,x)}>ABC</button></div>)}</div><div className="sat-question-actions"><button disabled={i===0} onClick={()=>setI(v=>v-1)}>Back</button>{i<questions.length-1?<button className="next" onClick={()=>setI(v=>v+1)}>Next</button>:<Link className="next" href={examHref('/exams/review',exam)}>Review</Link>}</div></section>
  </main>
  <footer className="sat-bottom"><button disabled={i===0} onClick={()=>setI(v=>v-1)}>‹</button><div ref={stripRef} className="sat-strip">{questions.map((_,x)=><button key={x} aria-current={x===i?'step':undefined} className={`${x===i?'current ':''}${answers[x]!==null?'answered ':''}${flags[x]?'marked':''}`} onClick={()=>setI(x)}>{x+1}</button>)}</div><div className="sat-legend"><span>━ Current</span><span>✓ Answered</span><span>⚑ Marked</span><span>○ Not Answered</span></div><span>{answered} of {questions.length} Answered</span><button disabled={i===questions.length-1} onClick={()=>setI(v=>v+1)}>›</button></footer>
 </div>
 {menu&&<div className="overlay"><section className="question-menu"><header><div><b>Questions</b><span>{answered} answered · {flags.filter(Boolean).length} marked</span></div><button onClick={()=>setMenu(false)}>×</button></header><div className="question-grid">{questions.map((_,x)=><button key={x} className={`${x===i?'current ':''}${answers[x]!==null?'answered ':''}${flags[x]?'flagged':''}`} onClick={()=>{setI(x);setMenu(false)}}>{x+1}</button>)}</div></section></div>}
 {noteOpen&&<div className="overlay"><section className="modal-card"><header><b>Question {i+1} Notes</b><button onClick={()=>setNoteOpen(false)}>×</button></header><textarea value={notes[i]||''} onChange={e=>setNote(i,e.target.value)} placeholder="Write a note..."/><button className="primary" onClick={()=>setNoteOpen(false)}>Save</button></section></div>}
 {calc&&<div className="overlay"><section className="modal-card calculator"><header><b>Calculator</b><button onClick={()=>setCalc(false)}>×</button></header><FunctionalCalculator/></section></div>}
 {ref&&<div className="overlay"><section className="modal-card reference"><header><b>Reference Sheet</b><button onClick={()=>setRef(false)}>×</button></header><div className="formula-grid"><article><b>Circle</b><span>A = πr²</span><span>C = 2πr</span></article><article><b>Triangle</b><span>A = ½bh</span><span>c² = a² + b²</span></article><article><b>Rectangular Prism</b><span>V = lwh</span></article><article><b>Cylinder</b><span>V = πr²h</span></article></div></section></div>}
 {shortcuts&&<div className="overlay"><section className="modal-card"><header><b>Keyboard Shortcuts</b><button onClick={()=>setShortcuts(false)}>×</button></header></section></div>}{toast&&<div className="exam-toast">{toast}</div>}
 </ExamFrame>
}

function ActSession(){
 const {answers,flags,eliminated,setAnswer,toggleFlag,toggleEliminate,questions,exam,timeLeft,setActiveQuestion}=useExam();
 const [i,setI]=useState(0);const [font,setFont]=useState(17);const [lineHeight,setLineHeight]=useState(1.65);const [calc,setCalc]=useState(false);const [toast,setToast]=useState('');const [timerHidden,setTimerHidden]=useState(false);const [passageWidth,setPassageWidth]=useState(50);const [resizing,setResizing]=useState(false);const [toolsOpen,setToolsOpen]=useState(false);const [notesOpen,setNotesOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const [focus,setFocus]=useState(false);const [underlineMode,setUnderlineMode]=useState(false);
 const passageRef=useRef<HTMLElement>(null);const workspaceRef=useRef<HTMLElement>(null);const stripRef=useRef<HTMLDivElement>(null);const q=questions[i];const section=exam.blueprint.section;const hasPassage=Boolean(q.passage);const answered=answers.filter(v=>v!==null).length;const sectionName=section.replaceAll('_',' ');const minutes=String(Math.floor(timeLeft/60)).padStart(2,'0');const seconds=String(timeLeft%60).padStart(2,'0');
 const showToast=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),1800)};
 useEffect(()=>{setActiveQuestion(i);passageRef.current?.scrollTo({top:0,behavior:'smooth'});stripRef.current?.querySelector(`[aria-current="step"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})},[i,setActiveQuestion]);
 useEffect(()=>{if(!resizing)return;const move=(e:PointerEvent)=>{const box=workspaceRef.current?.getBoundingClientRect();if(!box)return;setPassageWidth(Math.min(67,Math.max(40,((e.clientX-box.left)/box.width)*100)))};const up=()=>setResizing(false);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});return()=>window.removeEventListener('pointermove',move)},[resizing]);
 const markSelection=(mode:'highlight'|'underline')=>{const sel=window.getSelection();if(!sel||sel.rangeCount===0||sel.isCollapsed){showToast('Select passage text first');return}const range=sel.getRangeAt(0);if(!passageRef.current?.contains(range.commonAncestorContainer)){showToast('Select text in the passage');return}try{const el=document.createElement(mode==='highlight'?'mark':'span');el.className=mode==='highlight'?'act-student-highlight':'student-underline';range.surroundContents(el);sel.removeAllRanges()}catch{showToast('Select a smaller text segment')}};
 return <ExamFrame hideHeader><div className={`act-official-shell ${focus?'is-focus':''}`} dir="ltr">
  <header className="act-official-top"><div className="act-logo-text">ACT<sup>®</sup></div><button>{sectionName}⌄</button><button>Passage 1 of 4⌄</button><div className="act-top-spacer"/><div className="act-dropdown-anchor"><button onClick={()=>setToolsOpen(v=>!v)}>☷ Tools⌄</button>{toolsOpen&&<div className="act-official-menu"><button onClick={()=>setFocus(v=>!v)}>Focus</button><button onClick={()=>setLineHeight(v=>v>=2.1?1.5:v+.2)}>Line Spacing</button><button onClick={()=>markSelection('underline')}>Underline</button><button onClick={()=>markSelection('highlight')}>Highlight</button><button onClick={()=>setFont(v=>Math.min(23,v+1))}>Increase Text</button><button onClick={()=>setFont(v=>Math.max(14,v-1))}>Decrease Text</button></div>}</div><div className="act-dropdown-anchor"><button onClick={()=>setNotesOpen(v=>!v)}>✎ Highlights & Notes⌄</button>{notesOpen&&<div className="act-official-menu notes"><button onClick={()=>markSelection('highlight')}>Highlight selected text</button><button onClick={()=>markSelection('underline')}>Underline selected text</button></div>}</div><div className="act-dropdown-anchor"><button onClick={()=>setMoreOpen(v=>!v)}>⋮ More⌄</button>{moreOpen&&<div className="act-official-menu"><button onClick={()=>showToast('Keyboard shortcuts enabled')}>Keyboard shortcuts</button><button onClick={()=>showToast('Help opened')}>Help</button>{section==='MATH'&&<button onClick={()=>setCalc(true)}>Calculator</button>}</div>}</div><div className="act-time"><small>Time Remaining</small><b>{timerHidden?'••:••':`${minutes}:${seconds}`}</b></div><button className="act-hide-time" onClick={()=>setTimerHidden(v=>!v)}>◉ {timerHidden?'Show':'Hide'}</button></header>
  <main ref={workspaceRef} className={`act-official-workspace ${hasPassage?'has-passage':''}`} style={hasPassage?({'--act-passage':`${passageWidth}%`} as React.CSSProperties):undefined}>
   {hasPassage&&<section className="act-official-passage"><header>PASSAGE 1</header><article ref={passageRef} style={{fontSize:font,lineHeight}}><h2>Improving the Way We Learn</h2>{q.passage?.split('\n\n').map((x,n)=><p key={n}><span className="line-no">{n===0?'1':n*5}</span>{x}</p>)}</article><footer><span>⌕ Zoom</span><span>Word Count: {q.passage?.trim().split(/\s+/).length||0}</span></footer></section>}
   {hasPassage&&<button className="act-official-divider" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setResizing(true)}}>‹›</button>}
   <section className="act-official-question"><header><span>Question {i+1} of {questions.length}</span><button className={flags[i]?'marked':''} onClick={()=>toggleFlag(i)}>♧ Mark for Review</button></header><h1><span>{i+1}.</span><span dangerouslySetInnerHTML={{__html:q.prompt}}/></h1><div className="act-official-choices">{q.choices.map((c,x)=><button key={c.id} className={`${answers[i]===x?'selected':''} ${eliminated[i]?.includes(x)?'eliminated':''}`} onClick={()=>setAnswer(i,x)}><b>{String.fromCharCode(65+x)}</b><span dangerouslySetInnerHTML={{__html:c.text}}/><i onClick={e=>{e.stopPropagation();toggleEliminate(i,x)}}>⊘</i></button>)}</div><div className="act-inline-nav"><button disabled={i===0} onClick={()=>setI(v=>v-1)}>Back</button>{i<questions.length-1?<button className="next" onClick={()=>setI(v=>v+1)}>Next</button>:<Link className="next" href={examHref('/exams/review',exam)}>Review</Link>}</div></section>
   <aside className="act-side-tools"><button onClick={()=>setFocus(v=>!v)}>☷<span>Focus</span></button><button onClick={()=>setLineHeight(v=>v>=2.1?1.5:v+.2)}>☷<span>Line<br/>Spacing</span></button><button className={underlineMode?'active':''} onClick={()=>{setUnderlineMode(v=>!v);markSelection('underline')}}><u>U</u><span>Underline</span></button><button onClick={()=>markSelection('highlight')}>◆<span>Highlight</span></button><button onClick={()=>setFont(v=>Math.min(23,v+1))}>+A<span>Increase<br/>Text</span></button><button onClick={()=>setFont(v=>Math.max(14,v-1))}>−A<span>Decrease<br/>Text</span></button></aside>
  </main>
  <footer className="act-official-bottom"><button disabled={i===0} onClick={()=>setI(v=>v-1)}>‹</button><div ref={stripRef} className="act-official-strip">{questions.map((_,x)=><button key={x} aria-current={x===i?'step':undefined} className={`${x===i?'current ':''}${answers[x]!==null?'answered ':''}${flags[x]?'marked':''}`} onClick={()=>setI(x)}>{x+1}</button>)}</div><div className="act-official-legend"><span>━ Current</span><span>✓ Answered</span><span>⚑ Marked</span><span>○ Not Answered</span></div><span>{answered} of {questions.length} Answered</span><button disabled={i===questions.length-1} onClick={()=>setI(v=>v+1)}>›</button></footer>
 </div>{calc&&<div className="overlay"><section className="modal-card calculator"><header><b>Calculator</b><button onClick={()=>setCalc(false)}>×</button></header><FunctionalCalculator/></section></div>}{toast&&<div className="exam-toast">{toast}</div>}</ExamFrame>
}


function EstSession(){
 const {answers,flags,setAnswer,toggleFlag,questions,exam,timeLeft,setActiveQuestion}=useExam();
 const [active,setActive]=useState(0);const [timerHidden,setTimerHidden]=useState(false);const [view,setView]=useState<'paper'|'digital'>('paper');
 const questionRefs=useRef<Array<HTMLElement|null>>([]);const answered=answers.filter(v=>v!==null).length;const mins=String(Math.floor(timeLeft/60)).padStart(2,'0');const secs=String(timeLeft%60).padStart(2,'0');
 const sectionName=exam.blueprint.section.replaceAll('_',' ');const firstPassage=questions.find(q=>q.passage)?.passage||'';
 useEffect(()=>{setActiveQuestion(active)},[active,setActiveQuestion]);
 const goTo=(index:number)=>{setActive(index);questionRefs.current[index]?.scrollIntoView({behavior:'smooth',block:'center'})};
 return <ExamFrame hideHeader><div className="est-shell" dir="ltr">
  <header className="est-topbar"><div><b>MASTERY EST</b><span>Paper Simulation</span></div><div className="est-section-title"><b>{sectionName}</b><small>{answered} of {questions.length} answered</small></div><div className="est-view-toggle"><button className={view==='paper'?'active':''} onClick={()=>setView('paper')}>Paper View</button><button className={view==='digital'?'active':''} onClick={()=>setView('digital')}>Digital View</button></div><button className="est-timer" onClick={()=>setTimerHidden(v=>!v)}><small>Time Remaining</small><b>{timerHidden?'••:••':`${mins}:${secs}`}</b><span>{timerHidden?'Show':'Hide'}</span></button></header>
  {view==='paper'?<main className="est-paper-workspace">
   <aside className="est-bubble-sheet"><header><b>ANSWER SHEET</b><span>Fill one bubble for each question</span></header><div className="est-bubble-columns"><span>No.</span><span>A</span><span>B</span><span>C</span><span>D</span><span>Review</span></div><div className="est-bubble-list">{questions.map((q,i)=><div key={q.id} className={`est-bubble-row ${i===active?'current':''}`}><button className="est-q-number" onClick={()=>goTo(i)}>{i+1}</button>{q.choices.map((c,x)=><button key={c.id} aria-label={`Question ${i+1}, choice ${c.id}`} className={`est-bubble ${answers[i]===x?'filled':''}`} onClick={()=>{setAnswer(i,x);setActive(i)}}><span>{c.id}</span></button>)}<button className={`est-review-dot ${flags[i]?'marked':''}`} onClick={()=>toggleFlag(i)}>⚑</button></div>)}</div><footer><div><i className="sample-bubble filled"/><span>Answered</span></div><div><i className="sample-bubble"/><span>Blank</span></div><div><i className="sample-review">⚑</i><span>Review</span></div></footer></aside>
   <section className="est-paper-stage"><article className="est-paper-page"><header><div><b>EST</b><span>Egyptian Scholastic Test</span></div><div><strong>{sectionName}</strong><small>Practice Test</small></div><em>Page 1</em></header>{firstPassage&&<section className="est-paper-passage"><div className="est-paper-rule">Questions 1–{questions.length} are based on the following passage.</div><h1>Improving the Way We Learn</h1>{firstPassage.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</section>}<section className="est-paper-questions">{questions.map((q,i)=><article key={q.id} ref={el=>{questionRefs.current[i]=el}} className={`est-paper-question ${i===active?'active':''}`} onClick={()=>setActive(i)}><header><b>{i+1}</b><button className={flags[i]?'marked':''} onClick={e=>{e.stopPropagation();toggleFlag(i)}}>{flags[i]?'Marked':'Mark for review'}</button></header><div className="est-paper-prompt" dangerouslySetInnerHTML={{__html:q.prompt}}/><ol>{q.choices.map((c,x)=><li key={c.id} className={answers[i]===x?'selected':''} onClick={e=>{e.stopPropagation();setAnswer(i,x);setActive(i)}}><b>{c.id}.</b><span dangerouslySetInnerHTML={{__html:c.text}}/></li>)}</ol></article>)}</section><footer><span>Unauthorized reproduction is prohibited.</span><b>CONTINUE</b></footer></article></section>
  </main>:<main className="est-digital-workspace"><section><h2>{sectionName}</h2><p>{firstPassage}</p></section><section>{questions.map((q,i)=><article key={q.id}><b>Question {i+1}</b><div dangerouslySetInnerHTML={{__html:q.prompt}}/>{q.choices.map((c,x)=><button key={c.id} className={answers[i]===x?'selected':''} onClick={()=>setAnswer(i,x)}>{c.id}. <span dangerouslySetInnerHTML={{__html:c.text}}/></button>)}</article>)}</section></main>}
  <footer className="est-bottom"><span>Paper simulation mirrors the habit of marking answers separately from the test booklet.</span><div><button disabled={active===0} onClick={()=>goTo(active-1)}>Previous</button>{active<questions.length-1?<button className="primary" onClick={()=>goTo(active+1)}>Next Question</button>:<Link className="primary" href={examHref('/exams/review',exam)}>Review Answers</Link>}</div></footer>
 </div></ExamFrame>
}

function FunctionalCalculator(){const [display,setDisplay]=useState('0');const [expr,setExpr]=useState('');const press=(v:string)=>{if(v==='C'){setExpr('');setDisplay('0');return}if(v==='='){try{const safe=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-');const result=Function(`"use strict";return (${safe})`)();setExpr(String(result));setDisplay(String(result))}catch{setDisplay('Error')}return}const next=expr+v;setExpr(next);setDisplay(next)};return <><div className="calc-screen">{display}</div><div className="calc-grid">{['C','(',')','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','%','='].map(v=><button key={v} onClick={()=>press(v)}>{v}</button>)}</div></>}
function SessionPage(){const params=useSearchParams();const exam=buildProfileExam(params.get('exam'),params.get('section'),params.get('module'));return <ExamProvider exam={exam}>{exam.blueprint.exam==='ACT'?<ActSession/>:exam.blueprint.exam==='EST'?<EstSession/>:<StandardSession/>}</ExamProvider>}
export default function Page(){return <Suspense fallback={<main className="center-page">Loading exam…</main>}><SessionPage/></Suspense>}
